/* pc-alertas.js — popup "Esteja por dentro do mercado imobiliário": canal (e-mail/WhatsApp) + bairros. Reexibe 1x ao tentar sair para pedir login. */
(function(){
  if(/central\.html|crm\.html|adm/.test(location.pathname))return;
  var K='pc_alert',now=Date.now(),st={};try{st=JSON.parse(localStorage.getItem(K)||'{}')}catch(e){}
  if(st.done||(st.seen&&now-st.seen<7*864e5))return;
  var B=['Zona Sul','Barra da Tijuca','Porto Maravilha / Centro','Zona Norte','Jacarepaguá','Niterói','Campo Grande','Búzios e Lagos','Alto padrão'];
  var css=document.createElement('style');css.textContent='#pca{position:fixed;inset:0;background:rgba(5,12,24,.7);z-index:99999;display:none;align-items:center;justify-content:center;padding:14px}#pca .bx{background:#fff;color:#1b2433;border-radius:18px;max-width:460px;width:100%;max-height:92vh;overflow:auto;padding:22px;font:15px/1.5 system-ui,sans-serif}#pca h3{margin:0 0 4px;font-size:21px;color:#0b1b33}#pca .ch{display:flex;flex-wrap:wrap;gap:8px;margin:8px 0}#pca .ch label{border:1px solid #cfd6e0;border-radius:99px;padding:8px 12px;cursor:pointer;min-height:40px;display:flex;align-items:center}#pca .ch label{position:relative}#pca .ch input{position:absolute;opacity:0;width:1px;height:1px}#pca .ch label:focus-within{outline:2px solid #0b1b33}#pca .ch input:checked+span{font-weight:700;color:#0b1b33}#pca .ch label:has(input:checked){background:#d9a441;border-color:#d9a441}#pca input[type=text],#pca input[type=email],#pca input[type=tel]{width:100%;min-height:44px;margin:4px 0;padding:8px 12px;border:1px solid #cfd6e0;border-radius:10px;font:inherit}#pca button{min-height:46px;border:0;border-radius:99px;padding:0 20px;font-weight:700;cursor:pointer;font-size:15px}#pca .p{background:#d9a441;color:#1b1304;width:100%;margin-top:8px}#pca .s{background:none;color:#5b6676;width:100%;font-weight:500}#pca small{color:#5b6676}';document.head.appendChild(css);
  var d=document.createElement('div');d.id='pca';d.setAttribute('role','dialog');d.setAttribute('aria-modal','true');
  function tela1(sair){d.innerHTML='<div class="bx"><h3>'+(sair?'Antes de ir: fique por dentro do mercado':'Esteja por dentro do mercado imobiliário')+'</h3><p>Eu te aviso primeiro sobre lançamentos, condições e oportunidades do Rio. Escolha como e onde.</p><div class="ch"><label><input type="radio" name="cn" value="WhatsApp" checked><span>WhatsApp</span></label><label><input type="radio" name="cn" value="E-mail"><span>E-mail</span></label></div><b>Quais bairros te interessam?</b><div class="ch">'+B.map(function(b){return '<label><input type="checkbox" name="bz" value="'+b+'"><span>'+b+'</span></label>'}).join('')+'</div><input type="text" id="pn" placeholder="Seu nome" autocomplete="name"><input type="tel" id="pt" placeholder="WhatsApp com DDD" autocomplete="tel"><input type="email" id="pe" placeholder="E-mail" autocomplete="email"><label style="display:flex;gap:8px;margin:8px 0"><input type="checkbox" id="pl"> <small>Aceito receber atualizações do corretor Paulo Cotrim. Posso sair quando quiser (LGPD).</small></label><button class="p" id="pok">Quero receber</button><button class="s" id="pno">Agora não</button><div id="pgb" style="margin-top:6px"></div></div>';
    d.querySelector('#pno').onclick=function(){fecha(sair)};d.querySelector('#pok').onclick=enviar}
  function fecha(fim){d.style.display='none';st.seen=Date.now();if(fim)st.seen=Date.now();try{localStorage.setItem(K,JSON.stringify(st))}catch(e){}}
  function enviar(){var q=function(s){return d.querySelector(s)},nome=q('#pn').value.trim(),tel=q('#pt').value.trim(),em=q('#pe').value.trim(),cn=q('input[name=cn]:checked').value,bz=[].map.call(d.querySelectorAll('input[name=bz]:checked'),function(x){return x.value});
    if(!nome||(cn=='WhatsApp'&&tel.replace(/\D/g,'').length<10)||(cn=='E-mail'&&!/.+@.+\..+/.test(em))||!q('#pl').checked){alert('Preencha nome, o contato do canal escolhido e aceite o aviso.');return}
    var lead={nome:nome,telefone:tel,email:em,interesse:'Alertas de mercado: '+(bz.join(', ')||'todos os bairros'),regiao:bz.join(', '),origem:'site:alertas-'+(cn=='WhatsApp'?'whatsapp':'email'),temp:'morno',obs:'Quer receber por '+cn,extras:{canal:cn,bairros:bz,pagina:location.pathname}};
    if(window.enviarLeadCRM)window.enviarLeadCRM(lead);st.done=1;try{localStorage.setItem(K,JSON.stringify(st))}catch(e){}
    d.querySelector('.bx').innerHTML='<h3>Pronto, '+nome.split(' ')[0]+'!</h3><p>Você vai receber as novidades de '+(bz.join(', ')||'todo o Rio')+' por '+cn+'.</p><a class="p" style="display:flex;align-items:center;justify-content:center;text-decoration:none;min-height:46px;border-radius:99px;background:#d9a441;color:#1b1304;font-weight:700" target="_blank" rel="noopener" href="https://wa.me/5521989150864?text='+encodeURIComponent('Olá Paulo, acabei de me cadastrar nos alertas ('+(bz.join(', ')||'Rio')+')')+'">Falar com o Paulo agora</a><button class="s" onclick="document.getElementById(\'pca\').style.display=\'none\'">Fechar</button>'}
  function abre(sair){if(st.done||d.style.display=='flex')return;tela1(sair);d.style.display='flex'}
  document.body.appendChild(d);
  var shown=false;function once(s){if(shown)return;shown=true;abre(s)}
  setTimeout(function(){once(false)},30000);
  document.addEventListener('mouseout',function(e){if(e.clientY<=0&&!e.relatedTarget)once(true)});
  document.addEventListener('keydown',function(e){if(e.key=='Escape'&&d.style.display=='flex')fecha()});
})();
