/* CRM MAX — Central de leads, tags, filtros salvos, ações em massa, pipeline arrastável, valor/comissão, perda, score explicado,
   modelos e cadência, voz, agenda, match, proposta PDF, painel/funil/fontes/previsão, lembretes, backup, LGPD, atalhos, modo escuro, app */
(function(){
var $=function(i){return document.getElementById(i)};
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function sa(s){return String(s||'').normalize('NFD').replace(/[̀-ͯ]/g,'').toLowerCase()}
function iso(d){return (d||new Date()).toISOString().slice(0,10)}
function brl(v){return v?'R$ '+Math.round(v).toLocaleString('pt-BR'):'—'}
function L(){return getLeads()}function S(x){saveLeads(x);try{updateBadge()}catch(e){}}
function get(id){return L().filter(function(x){return x.id==id})[0]}
function upd(id,fn,a,d){var X=L(),l=X.filter(function(x){return x.id==id})[0];if(!l)return;fn(l);if(a)(l.hist=l.hist||[]).unshift({a:a,d:d||'',t:new Date().toLocaleString('pt-BR')});l.mod=Date.now();S(X);return l}
function dias(l){var t=l.ult||l.mod||l.id;return Math.floor((Date.now()-t)/864e5)}
var ETAPAS=[['novo','Novo'],['contato','Contato'],['visita','Visita'],['proposta','Proposta'],['fechado','Fechado'],['perdido','Perdido']];
/* ---------- score explicado ---------- */
function score(l){var r=[],s=0,add=function(p,t){s+=p;r.push((p>0?'+':'')+p+' '+t)};
 add(l.temp==='quente'?35:l.temp==='morno'?18:5,'temperatura '+(l.temp||'frio'));
 var st={proposta:22,visita:18,contato:10,novo:8}[l.status||'novo'];if(st)add(st,'etapa '+(l.status||'novo'));
 if(l.renda||l.orcamento)add(10,'renda/orçamento informado');if(l.tel)add(5,'tem WhatsApp');if(l.email)add(3,'tem e-mail');
 var d=dias(l);if(d<=1)add(12,'contato recente');else if(d>7)add(-12,d+' dias parado');
 if(/kit:(reserva|negocia|video|docs)/.test(l.origem||''))add(15,'pediu negociação no site');
 return{v:Math.max(0,Math.min(100,s)),r:r}}
window.scoreLead=score;
/* ---------- match lead × imóvel ---------- */
function match(l){var I=getImoveis(),r=parseFloat(l.renda)||0,b=sa(l.bairro),q=(String(l.interesse||'')+' '+(l.tipo||'')).match(/(\d)\s*q/i),qt=q?+q[1]:0;
 return I.map(function(i){var p=0,why=[];var reg=sa(i.regiao+' '+i.loc);if(b&&reg.indexOf(b)>=0){p+=40;why.push('bairro')}
  if(r&&i.rendaMin){if(i.rendaMin<=r){p+=35;why.push('cabe na renda')}else p-=30}
  if(qt&&new RegExp(qt+'\\s*(e\\s*\\d\\s*)?quarto','i').test(i.roi||'')){p+=15;why.push(qt+' quartos')}
  if(sa(l.interesse).indexOf(sa(i.nome))>=0){p+=30;why.push('já demonstrou interesse')}
  return{i:i,p:p,why:why}}).filter(function(x){return x.p>0}).sort(function(a,b){return b.p-a.p}).slice(0,3)}
window.matchLead=match;
/* ---------- modelos e cadência ---------- */
var MODELOS={
 'Boas-vindas':'Olá {nome}, aqui é o Paulo Cotrim, corretor no Rio. Recebi seu contato{bairro}. Pra eu te mandar só o que faz sentido: é pra morar ou investir, e qual faixa de valor?',
 'Follow-up':'Oi {nome}, tudo bem? Conseguiu ver o material que te enviei? Separei uma condição nova{bairro} — posso te mostrar em 10 minutos por videochamada?',
 'Pós-visita':'{nome}, obrigado pela visita! O que mais te agradou? Se quiser, já simulo entrada e parcela da unidade que você gostou.',
 'Proposta':'{nome}, preparei sua proposta com as condições que conversamos. Te envio agora e explico por chamada rápida?',
 'Reativação':'Oi {nome}! Faz um tempo que conversamos. Chegaram lançamentos{bairro} com condições de pré-lançamento. Quer receber?',
 'Aniversário':'{nome}, feliz aniversário! Muita saúde e conquistas — conte comigo sempre. Abraço, Paulo Cotrim.'};
function msg(k,l){return MODELOS[k].replace(/\{nome\}/g,String(l.nome||'').split(' ')[0]).replace(/\{bairro\}/g,l.bairro?' em '+l.bairro:'')}
var CAD=[0,1,3,7,15];
window.iniciarCadencia=function(id){var b=new Date();upd(id,function(l){l.cad=CAD.map(function(d,i){var x=new Date(b);x.setDate(x.getDate()+d);return{d:iso(x),k:['Boas-vindas','Follow-up','Follow-up','Reativação','Reativação'][i],ok:false}});l.retorno=l.cad[1].d},'Cadência iniciada','5 toques: dia 0, 1, 3, 7, 15');toast('Cadência criada — aparece na Agenda');};
/* ---------- proposta PDF ---------- */
window.propostaPDF=function(id){var l=get(id);if(!l)return;var m=match(l),im=(m[0]||{}).i||{};
 var nome=prompt('Empreendimento da proposta:',im.nome||'')||'';var i=getImoveis().filter(function(x){return sa(x.nome)===sa(nome)})[0]||im;
 var val=prompt('Valor da unidade (R$):',String(i.preco||'').replace(/\D/g,''))||'',ent=prompt('Entrada (R$):','')||'',un=prompt('Unidade / planta:','')||'';
 var w=window.open('','_blank');w.document.write("<html><head><meta charset='utf-8'><title>Proposta · "+esc(l.nome)+"</title><link href='https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@500&family=Inter:wght@400;600&display=swap' rel='stylesheet'><style>body{font-family:Inter,sans-serif;max-width:760px;margin:30px auto;padding:0 26px;color:#1a1a19;font-size:13.5px;line-height:1.7}h1,h2{font-family:'Cormorant Garamond',serif;font-weight:500}h1{font-size:40px;margin:6px 0}table{width:100%;border-collapse:collapse;margin:18px 0}td{padding:10px;border-bottom:1px solid #e3ddd1}td:first-child{color:#8a857b;width:40%}.t{display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid #b0895b;padding-bottom:12px}@media print{.np{display:none}}</style></head><body><div class='t'><img src='"+location.origin+"/logo-premium.svg' style='width:230px'><button class='np' onclick='print()' style='background:#b0895b;border:none;padding:10px 16px;border-radius:3px'>Salvar PDF</button></div><p style='color:#b0895b;letter-spacing:.2em;font-size:10px;margin-top:20px'>PROPOSTA COMERCIAL</p><h1>"+esc(i.nome||nome)+"</h1><p>Preparada para <b>"+esc(l.nome)+"</b> · "+new Date().toLocaleDateString('pt-BR')+"</p><table><tr><td>Unidade / planta</td><td>"+esc(un||i.roi||'A definir')+"</td></tr><tr><td>Localização</td><td>"+esc(i.loc||'')+"</td></tr><tr><td>Valor</td><td><b>"+esc(val?brl(+val.replace(/\D/g,'')):i.preco||'')+"</b></td></tr><tr><td>Entrada</td><td>"+esc(ent?brl(+ent.replace(/\D/g,'')):'A combinar')+"</td></tr><tr><td>Saldo</td><td>Financiamento bancário / parcelas com a construtora, conforme tabela vigente</td></tr></table><p>Próximos passos: 1) confirmar unidade, 2) análise de crédito, 3) reserva e assinatura.</p><p style='font-size:11px;color:#8a857b;border-top:1px solid #e3ddd1;padding-top:10px;margin-top:24px'>Proposta sujeita à disponibilidade e às condições da tabela oficial vigente da construtora. Paulo Cotrim · CRECI-RJ 77677-F · (21) 98915-0864 · www.paulocotrim.com</p></body></html>");w.document.close();
 upd(id,function(l){l.status=l.status==='novo'||l.status==='contato'?'proposta':l.status;l.valor=+String(val).replace(/\D/g,'')||l.valor},'Proposta gerada',i.nome||nome)};
/* ---------- perfil: score, match, modelos, cadência, agenda, voz, proposta ---------- */
var _vp=window.verPerfil;window.verPerfil=function(id){_vp(id);var mb=$('modal-profile-body'),l=get(id);if(!mb||!l)return;var sc=score(l),m=match(l);
 var h="<div style='border:1px solid #e3ddd1;border-radius:6px;padding:14px;margin-top:14px'><div style='display:flex;justify-content:space-between'><b>Score "+sc.v+"/100</b><small style='color:#8a857b'>"+(l.tags||[]).map(esc).join(' · ')+"</small></div><div style='font-size:12px;color:#8a857b;margin-top:4px'>"+sc.r.map(esc).join(' · ')+"</div></div>";
 h+="<div style='margin-top:12px'><div class='eyebrow'>Imóveis para "+esc(String(l.nome).split(' ')[0])+"</div>"+(m.length?m.map(function(x){return "<div style='display:flex;justify-content:space-between;gap:8px;padding:8px 0;border-bottom:1px solid #efe9df'><span><b>"+esc(x.i.nome)+"</b><br><small style='color:#8a857b'>"+esc(x.why.join(', '))+" · "+esc(x.i.preco||'')+"</small></span><button class='btn-cancel' onclick='enviarMaterialPara("+x.i.id+","+id+")'>Enviar</button></div>"}).join(''):"<small>Informe bairro, renda ou quartos em Editar lead para receber sugestões.</small>")+"</div>";
 h+="<div style='margin-top:12px'><div class='eyebrow'>Mensagens prontas</div><div style='display:flex;flex-wrap:wrap;gap:6px;margin-top:6px'>"+Object.keys(MODELOS).map(function(k){return "<button class='btn-cancel' onclick=\"zap("+id+",decodeURIComponent('"+encodeURIComponent(msg(k,l))+"'))\">"+k+"</button>"}).join('')+"</div></div>";
 h+="<div style='display:flex;flex-wrap:wrap;gap:6px;margin-top:12px'><button class='btn-submit' onclick='iniciarCadencia("+id+")'>Iniciar cadência</button><button class='btn-cancel' onclick='agendar("+id+")'>Agendar visita/vídeo</button><button class='btn-cancel' onclick='propostaPDF("+id+")'>Gerar proposta PDF</button><button class='btn-cancel' onclick='notaVoz("+id+")'>🎙 Nota por voz</button></div>";
 if(l.cad)h+="<div style='margin-top:10px;font-size:12px'>"+l.cad.map(function(c){return (c.ok?'✓ ':'○ ')+c.d.split('-').reverse().slice(0,2).join('/')+' '+c.k}).join(' · ')+"</div>";
 mb.insertAdjacentHTML('beforeend',h)};
window.enviarMaterialPara=function(imId,leadId){var i=getImoveis().filter(function(x){return x.id==imId})[0],l=get(leadId);if(!i||!l)return;var base='https://www.paulocotrim.com/';
 zap(leadId,'Olá '+String(l.nome).split(' ')[0]+'! Separei o '+i.nome+' pra você:\n• Apresentação: '+(i.url?base+i.url:base+'#portfolio')+'\n• Estudo de rentabilidade: '+base+'estudo.html?emp='+encodeURIComponent(i.url||sa(i.nome).replace(/[^a-z0-9]+/g,'-'))+'\n'+(i.preco?'• '+i.preco+'\n':'')+'Posso te mostrar numa videochamada de 15 min?');
 upd(leadId,function(x){x.interesse=i.nome},'Material enviado',i.nome)};
window.agendar=function(id){var q=prompt('Data e hora (dd/mm hh:mm) e tipo — ex.: 15/10 14:00 vídeo');if(!q)return;var m=q.match(/(\d{1,2})\/(\d{1,2})\s*(\d{1,2}:\d{2})?\s*(.*)/);if(!m){toast('Formato: 15/10 14:00 vídeo');return}
 var d=new Date(new Date().getFullYear(),+m[2]-1,+m[1]);upd(id,function(l){(l.ag=l.ag||[]).push({d:iso(d),h:m[3]||'',t:m[4]||'visita'});if(['novo','contato'].indexOf(l.status||'novo')>=0)l.status='visita';l.retorno=iso(d)},'Agendado',q);toast('Agendado: '+q)};
window.notaVoz=function(id){var R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){var t=prompt('Seu navegador não grava voz aqui. Digite a nota (no celular, use o microfone do teclado):');if(t)upd(id,function(){},'Nota',t);return}
 var r=new R();r.lang='pt-BR';toast('Fale agora…');r.onresult=function(e){var t=e.results[0][0].transcript;upd(id,function(l){l.obs=(l.obs?l.obs+' · ':'')+t},'Nota por voz',t);toast('Nota salva: '+t.slice(0,40))};r.start()};
/* ---------- editar lead: tags, valor, comissão, motivo de perda ---------- */
var _el=window.editarLead;window.editarLead=function(id){_el(id);var o=$('el-obs');if(!o||$('el-tags'))return;var l=get(id)||{};
 o.closest('.form-group').insertAdjacentHTML('beforebegin',"<div class='form-group'><label class='form-label'>Tags (separe por vírgula)</label><input class='form-input' id='el-tags' value='"+esc((l.tags||[]).join(', '))+"' placeholder='investidor, MCMV, permuta'/></div><div class='form-group'><label class='form-label'>Valor do negócio (R$)</label><input class='form-input' id='el-valor' value='"+esc(l.valor||'')+"'/></div><div class='form-group'><label class='form-label'>Comissão (%)</label><input class='form-input' id='el-com' value='"+esc(l.com||'')+"' placeholder='ex.: 4'/></div><div class='form-group'><label class='form-label'>Aceita contato (LGPD)</label><select class='form-input' id='el-lgpd'><option value='sim'"+(l.lgpd!=='nao'?' selected':'')+">Sim</option><option value='nao'"+(l.lgpd==='nao'?' selected':'')+">Não — não contatar</option></select></div>");
 var ok=$('modal-el-ok'),f=ok.onclick;ok.onclick=function(){var st=$('el-status').value,mot='';if(st==='perdido'&&(get(id)||{}).status!=='perdido'){mot=prompt('Motivo da perda (obrigatório): preço, financiamento negado, comprou com outro, desistiu, sem retorno…');if(!mot){alert('Informe o motivo da perda');return}}
  var X=L(),x=X.filter(function(y){return y.id==id})[0];if(x){x.tags=$('el-tags').value.split(',').map(function(t){return t.trim()}).filter(Boolean);x.valor=+String($('el-valor').value).replace(/\D/g,'')||'';x.com=parseFloat(String($('el-com').value).replace(',','.'))||'';x.lgpd=$('el-lgpd').value;if(mot){x.motivo=mot;(x.hist=x.hist||[]).unshift({a:'Perdido',d:mot,t:new Date().toLocaleString('pt-BR')})}S(X)}f()}};
/* ---------- pipeline arrastável ---------- */
var _rp=window.renderPipeline;window.renderPipeline=function(){_rp();var b=$('pipeline-board');if(!b)return;
 [].forEach.call(b.querySelectorAll('.pipe-col'),function(col,ci){var k=['novo','contato','proposta','visita','fechado'][ci];col.addEventListener('dragover',function(e){e.preventDefault();col.style.outline='2px dashed #b0895b'});col.addEventListener('dragleave',function(){col.style.outline=''});
  col.addEventListener('drop',function(e){e.preventDefault();col.style.outline='';var id=e.dataTransfer.getData('id');if(id){upd(id,function(l){l.status=k},'Etapa: '+k,'pipeline');renderPipeline()}});
  [].forEach.call(col.querySelectorAll('.pipe-card'),function(c){var m=(c.getAttribute('onclick')||'').match(/\d+/);if(!m)return;c.draggable=true;c.addEventListener('dragstart',function(e){e.dataTransfer.setData('id',m[0])});var l=get(m[0]);if(l&&l.valor)c.insertAdjacentHTML('beforeend',"<div style='font-size:11px;color:#8a857b;margin-top:4px'>"+brl(l.valor)+"</div>")})});
 if(!$('pipe-tip'))b.insertAdjacentHTML('beforebegin',"<div id='pipe-tip' style='font-size:12px;color:#8a857b;margin-bottom:10px'>Arraste os cards entre as colunas para mudar a etapa.</div>")};
/* ---------- Central: busca global, filtros salvos, tags, ações em massa, agenda, painel ---------- */
function central(){var pg=$('page-central');if(!pg){pg=document.createElement('div');pg.className='page';pg.id='page-central';var ref=$('page-dashboard');ref.parentNode.insertBefore(pg,ref)}
 pg.innerHTML="<div style='display:flex;justify-content:space-between;align-items:flex-end;flex-wrap:wrap;gap:10px;margin-bottom:16px'><div><div class='eyebrow'>Central de vendas</div><div style='font-size:26px' class='page-title'>Leads, agenda e resultados</div></div><div style='display:flex;gap:6px'>"+['leads','agenda','painel','faxina'].map(function(t){return "<button class='btn-cancel ctab' data-t='"+t+"'>"+{leads:'Leads',agenda:'Agenda',painel:'Painel',faxina:'Faxina'}[t]+"</button>"}).join('')+"</div></div><div id='c-body'></div>";
 [].forEach.call(pg.querySelectorAll('.ctab'),function(b){b.onclick=function(){tab(b.dataset.t)}});tab(window.__ct||'leads')}
function tab(t){window.__ct=t;[].forEach.call(document.querySelectorAll('.ctab'),function(b){b.className=(b.dataset.t===t?'btn-submit':'btn-cancel')+' ctab'});({leads:tLeads,agenda:tAgenda,painel:tPainel,faxina:tFaxina})[t]()}
var FS=function(){try{return JSON.parse(localStorage.crm_filtros||'{}')}catch(e){return{}}};
function tLeads(){var X=L(),bs={},tg={};X.forEach(function(l){if(l.bairro)bs[l.bairro]=1;(l.tags||[]).forEach(function(t){tg[t]=1})});var fs=FS();
 $('c-body').innerHTML="<div class='card'><div class='card-body'><div style='display:grid;grid-template-columns:2fr 1fr 1fr 1fr 1fr;gap:8px'><input class='form-input' id='f-q' placeholder='Buscar nome, telefone, e-mail, bairro, fonte…'/>"
 +"<select class='form-input' id='f-b'><option value=''>Bairro</option>"+Object.keys(bs).sort().map(function(b){return '<option>'+esc(b)+'</option>'}).join('')+"</select>"
 +"<select class='form-input' id='f-t'><option value=''>Temperatura</option><option>quente</option><option>morno</option><option>frio</option></select>"
 +"<select class='form-input' id='f-s'><option value=''>Etapa</option>"+ETAPAS.map(function(e){return '<option value="'+e[0]+'">'+e[1]+'</option>'}).join('')+"</select>"
 +"<select class='form-input' id='f-g'><option value=''>Tag</option>"+Object.keys(tg).sort().map(function(t){return '<option>'+esc(t)+'</option>'}).join('')+"</select></div>"
 +"<div style='display:flex;gap:6px;flex-wrap:wrap;margin-top:10px;align-items:center'><button class='btn-cancel' id='f-save'>Salvar filtro</button>"+Object.keys(fs).map(function(n){return "<button class='btn-cancel fsv' data-n='"+esc(n)+"'>★ "+esc(n)+"</button>"}).join('')
 +"<span style='flex:1'></span><button class='btn-cancel' onclick='importarCSV()'>Importar planilha (CSV)</button><button class='btn-cancel' onclick='abrirImportFoto()'>Scanner / cartão de visita</button></div></div></div>"
 +"<div id='f-mass' style='display:none;margin:10px 0;gap:6px;flex-wrap:wrap;align-items:center'><b id='f-n'></b><select class='form-input' id='m-s' style='width:auto'><option value=''>Mudar etapa…</option>"+ETAPAS.map(function(e){return '<option value="'+e[0]+'">'+e[1]+'</option>'}).join('')+"</select><select class='form-input' id='m-t' style='width:auto'><option value=''>Temperatura…</option><option>quente</option><option>morno</option><option>frio</option></select><input class='form-input' id='m-g' placeholder='+ tag' style='width:120px'/><input class='form-input' id='m-b' placeholder='bairro' style='width:120px'/><button class='btn-submit' id='m-ok'>Aplicar</button><button class='btn-cancel' id='m-del'>Excluir</button></div>"
 +"<div class='card' style='margin-top:10px'><div style='overflow:auto'><table class='lead-table' style='width:100%'><thead><tr><th><input type='checkbox' id='f-all'/></th><th>Lead</th><th>Bairro</th><th>Temp.</th><th>Etapa</th><th>Fonte</th><th>Score</th><th>Retorno</th><th></th></tr></thead><tbody id='f-rows'></tbody></table></div><div id='f-pg' style='padding:10px;font-size:12px;display:flex;gap:8px;justify-content:flex-end'></div></div>";
 var pg=1;function filt(){var q=sa($('f-q').value),b=$('f-b').value,t=$('f-t').value,s=$('f-s').value,g=$('f-g').value;return L().filter(function(l){if(b&&l.bairro!==b)return false;if(t&&l.temp!==t)return false;if(s&&(l.status||'novo')!==s)return false;if(g&&(l.tags||[]).indexOf(g)<0)return false;if(q&&sa([l.nome,l.tel,l.email,l.bairro,l.fonte,l.origem,l.interesse,(l.tags||[]).join(' ')].join(' ')).indexOf(q)<0&&String(l.tel).replace(/\D/g,'').indexOf(q.replace(/\D/g,'')||'§')<0)return false;return true}).sort(function(a,b){return score(b).v-score(a).v})}
 function draw(){var F=filt(),per=50,mx=Math.max(1,Math.ceil(F.length/per));if(pg>mx)pg=mx;
  $('f-rows').innerHTML=F.slice((pg-1)*per,pg*per).map(function(l){var sc=score(l).v;return "<tr><td><input type='checkbox' class='f-ck' value='"+l.id+"'/></td><td><b class='lead-name' style='cursor:pointer' onclick='verPerfil("+l.id+")'>"+esc(l.nome)+"</b><br><small>"+esc(l.tel||'')+(l.lgpd==='nao'?' · não contatar':'')+"</small></td><td>"+esc(l.bairro||'')+"</td><td>"+esc(l.temp||'')+"</td><td>"+esc(l.status||'novo')+"</td><td><small>"+esc(l.fonte||l.origem||'')+"</small></td><td><b>"+sc+"</b></td><td><small>"+(l.retorno?l.retorno.split('-').reverse().slice(0,2).join('/'):'')+"</small></td><td style='white-space:nowrap'><button class='btn-cancel' onclick='ligar("+l.id+")'>Ligar</button> <button class='btn-cancel' onclick='zap("+l.id+")'>WhatsApp</button></td></tr>"}).join('')||"<tr><td colspan='9' style='padding:20px;text-align:center'>Nenhum lead com esse filtro.</td></tr>";
  $('f-pg').innerHTML=F.length+" leads · página "+pg+"/"+mx+" <button class='btn-cancel' id='pp'>‹</button><button class='btn-cancel' id='pn'>›</button>";$('pp').onclick=function(){pg=Math.max(1,pg-1);draw()};$('pn').onclick=function(){pg=Math.min(mx,pg+1);draw()};mass()}
 function sel(){return [].map.call(document.querySelectorAll('.f-ck:checked'),function(c){return c.value})}
 function mass(){var n=sel().length;$('f-mass').style.display=n?'flex':'none';$('f-n').textContent=n+' selecionado(s)'}
 ['f-q','f-b','f-t','f-s','f-g'].forEach(function(i){$(i).oninput=$(i).onchange=function(){pg=1;draw()}});
 $('c-body').addEventListener('change',function(e){if(e.target.id==='f-all'){[].forEach.call(document.querySelectorAll('.f-ck'),function(c){c.checked=e.target.checked})}if(/f-ck|f-all/.test(e.target.className+e.target.id))mass()});
 $('m-ok').onclick=function(){var ids=sel(),s=$('m-s').value,t=$('m-t').value,g=$('m-g').value.trim(),b=$('m-b').value.trim();if(s==='perdido'){var mo=prompt('Motivo da perda (obrigatório):');if(!mo)return}var X=L();X.forEach(function(l){if(ids.indexOf(String(l.id))<0)return;if(s)l.status=s;if(t)l.temp=t;if(g)l.tags=(l.tags||[]).concat([g]).filter(function(v,i,a){return a.indexOf(v)===i});if(b)l.bairro=b;if(s==='perdido')l.motivo=mo;(l.hist=l.hist||[]).unshift({a:'Ação em massa',d:[s,t,g,b].filter(Boolean).join(' · '),t:new Date().toLocaleString('pt-BR')})});S(X);toast(ids.length+' lead(s) atualizado(s)');draw()};
 $('m-del').onclick=function(){var ids=sel();if(!confirm('Excluir '+ids.length+' lead(s)?'))return;S(L().filter(function(l){return ids.indexOf(String(l.id))<0}));draw()};
 $('f-save').onclick=function(){var n=prompt('Nome do filtro (ex.: Quentes Barra):');if(!n)return;var f=FS();f[n]={q:$('f-q').value,b:$('f-b').value,t:$('f-t').value,s:$('f-s').value,g:$('f-g').value};localStorage.crm_filtros=JSON.stringify(f);tLeads()};
 [].forEach.call(document.querySelectorAll('.fsv'),function(b){b.onclick=function(){var f=FS()[b.dataset.n];['q','b','t','s','g'].forEach(function(k){$('f-'+k).value=f[k]||''});pg=1;draw()};b.oncontextmenu=function(e){e.preventDefault();if(confirm('Apagar filtro?')){var f=FS();delete f[b.dataset.n];localStorage.crm_filtros=JSON.stringify(f);tLeads()}}});
 draw()}
function tAgenda(){var X=L(),h=iso(),ev=[];X.forEach(function(l){if(l.status==='perdido'||l.status==='fechado')return;if(l.retorno)ev.push({d:l.retorno,l:l,t:'Retorno'});(l.ag||[]).forEach(function(a){ev.push({d:a.d,l:l,t:(a.t||'Visita')+(a.h?' '+a.h:'')})});(l.cad||[]).forEach(function(c){if(!c.ok)ev.push({d:c.d,l:l,t:'Cadência: '+c.k,cad:c})});if(!l.retorno&&dias(l)>=5&&l.status!=='novo')ev.push({d:h,l:l,t:'Parado há '+dias(l)+' dias'})});
 var days=[];for(var i=-1;i<7;i++){var d=new Date();d.setDate(d.getDate()+i);days.push(iso(d))}
 $('c-body').innerHTML="<div style='display:grid;grid-template-columns:repeat(4,1fr);gap:10px'>"+days.map(function(d){var E=ev.filter(function(e){return i===-1?false:(d===days[0]?e.d<=d:e.d===d)});var lab=d===h?'Hoje':d<h?'Atrasados':new Date(d+'T12:00').toLocaleDateString('pt-BR',{weekday:'short',day:'2-digit',month:'2-digit'});
  return "<div class='card'><div class='card-header'><div class='card-title'>"+lab+" <small style='color:#8a857b'>("+E.length+")</small></div></div><div class='card-body' style='max-height:320px;overflow:auto'>"+(E.map(function(e){return "<div style='padding:7px 0;border-bottom:1px solid #efe9df;font-size:12.5px'><b style='cursor:pointer' onclick='verPerfil("+e.l.id+")'>"+esc(e.l.nome)+"</b><br><small>"+esc(e.t)+(e.l.bairro?' · '+esc(e.l.bairro):'')+"</small><br><button class='btn-cancel' style='padding:3px 8px;margin-top:4px' onclick='ligar("+e.l.id+")'>Ligar</button> <button class='btn-cancel' style='padding:3px 8px' onclick=\"zap("+e.l.id+(e.cad?",decodeURIComponent('"+encodeURIComponent(msg(e.cad.k,e.l))+"')":"")+");cadOk("+e.l.id+",'"+(e.cad?e.cad.d:'')+"')\">WhatsApp</button></div>"}).join('')||"<small style='color:#8a857b'>Livre</small>")+"</div></div>"}).join('')+"</div>"}
window.cadOk=function(id,d){if(!d)return;upd(id,function(l){(l.cad||[]).forEach(function(c){if(c.d===d)c.ok=true});var n=(l.cad||[]).filter(function(c){return!c.ok})[0];l.retorno=n?n.d:l.retorno},'Toque da cadência',d)};
function tPainel(){var X=L(),sem=Date.now()-7*864e5,ev={lig:0,wa:0,vis:0,prop:0,fech:0};X.forEach(function(l){(l.hist||[]).forEach(function(h){var p=String(h.t).match(/(\d{2})\/(\d{2})\/(\d{4})/);if(!p)return;var t=new Date(+p[3],+p[2]-1,+p[1]).getTime();if(t<sem)return;if(/Liga/.test(h.a))ev.lig++;if(/WhatsApp|Material/.test(h.a))ev.wa++;if(/Agendado|visita/i.test(h.a))ev.vis++;if(/Proposta/.test(h.a))ev.prop++;if(/fechado/i.test(h.a))ev.fech++})});
 var tot=X.length,c=function(s){return X.filter(function(l){return ETAPAS.map(function(e){return e[0]}).indexOf(l.status||'novo')>=ETAPAS.map(function(e){return e[0]}).indexOf(s)&&l.status!=='perdido'}).length};
 var fun=['novo','contato','visita','proposta','fechado'].map(function(s){return[s,s==='novo'?tot-X.filter(function(l){return l.status==='perdido'}).length:c(s)]});
 var fon={};X.forEach(function(l){var f=String(l.fonte||l.origem||'Sem fonte').split(' · ')[0].split(':')[0];fon[f]=fon[f]||{n:0,f:0};fon[f].n++;if(l.status==='fechado')fon[f].f++});
 var prev=X.filter(function(l){return['proposta','visita'].indexOf(l.status)>=0&&l.valor}).reduce(function(a,l){return a+l.valor*((l.com||4)/100)*(l.status==='proposta'?.5:.25)},0),fe=X.filter(function(l){return l.status==='fechado'&&l.valor}).reduce(function(a,l){return a+l.valor*((l.com||4)/100)},0);
 var mot={};X.forEach(function(l){if(l.status==='perdido'&&l.motivo)mot[l.motivo]=(mot[l.motivo]||0)+1});
 $('c-body').innerHTML="<div class='kpi-row'>"+[['Ligações (7 dias)',ev.lig],['WhatsApps (7 dias)',ev.wa],['Visitas/vídeos',ev.vis],['Propostas',ev.prop]].map(function(k){return "<div class='kpi'><div class='kpi-label'>"+k[0]+"</div><div class='kpi-val'>"+k[1]+"</div></div>"}).join('')+"</div>"
 +"<div class='grid-2'><div class='card'><div class='card-header'><div class='card-title'>Funil e conversão</div></div><div class='card-body'>"+fun.map(function(f,i){var pc=fun[0][1]?Math.round(f[1]/fun[0][1]*100):0,cv=i&&fun[i-1][1]?Math.round(f[1]/fun[i-1][1]*100):100;return "<div style='margin-bottom:10px'><div style='display:flex;justify-content:space-between;font-size:12.5px'><span>"+f[0]+"</span><span>"+f[1]+" · "+cv+"% da etapa anterior</span></div><div style='height:8px;background:#efe9df;border-radius:4px'><div style='height:8px;width:"+pc+"%;background:#b0895b;border-radius:4px'></div></div></div>"}).join('')+"</div></div>"
 +"<div class='card'><div class='card-header'><div class='card-title'>Resultado por fonte</div></div><div class='card-body'>"+Object.keys(fon).sort(function(a,b){return fon[b].n-fon[a].n}).slice(0,10).map(function(f){return "<div style='display:flex;justify-content:space-between;padding:6px 0;border-bottom:1px solid #efe9df;font-size:12.5px'><span>"+esc(f)+"</span><span>"+fon[f].n+" leads · "+fon[f].f+" vendas</span></div>"}).join('')+"</div></div></div>"
 +"<div class='grid-2' style='margin-top:14px'><div class='card'><div class='card-header'><div class='card-title'>Comissão</div></div><div class='card-body'><div class='kpi-label'>Prevista (propostas e visitas, ponderada)</div><div class='kpi-val'>"+brl(prev)+"</div><div class='kpi-label' style='margin-top:10px'>Fechada</div><div class='kpi-val'>"+brl(fe)+"</div><small style='color:#8a857b'>Informe valor e % de comissão em Editar lead. Padrão 4%.</small></div></div>"
 +"<div class='card'><div class='card-header'><div class='card-title'>Motivos de perda</div></div><div class='card-body'>"+(Object.keys(mot).map(function(m){return "<div style='display:flex;justify-content:space-between;font-size:12.5px;padding:5px 0'><span>"+esc(m)+"</span><b>"+mot[m]+"</b></div>"}).join('')||"<small>Nenhuma perda registrada.</small>")+"</div></div></div>"}

function tFaxina(){var X=L(),h=iso(),tn=function(t){return String(t||'').replace(/\D/g,'').slice(-9)};
 var dup={},grp=[];X.forEach(function(l){var k=tn(l.tel)||(l.email||'').toLowerCase();if(!k)return;(dup[k]=dup[k]||[]).push(l)});Object.keys(dup).forEach(function(k){if(dup[k].length>1)grp.push(dup[k])});
 var ativo=function(l){return l.status!=='perdido'&&l.status!=='fechado'};
 var P=[
  ['dup','Duplicados (mesmo telefone/e-mail)',grp.length+' grupo(s)',grp],
  ['fonte','Sem fonte',null,X.filter(function(l){return !(l.fonte||l.origem)})],
  ['bairro','Sem bairro',null,X.filter(function(l){return ativo(l)&&!l.bairro})],
  ['tel','Sem telefone',null,X.filter(function(l){return !tn(l.tel)})],
  ['parado','Parados há 7+ dias sem retorno marcado',null,X.filter(function(l){return ativo(l)&&dias(l)>=7&&!(l.retorno&&l.retorno>=h)})],
  ['novo','Em "Novo" há 3+ dias (já deviam ter avançado)',null,X.filter(function(l){return (l.status||'novo')==='novo'&&dias(l)>=3})],
  ['perda','Perdidos sem motivo',null,X.filter(function(l){return l.status==='perdido'&&!l.motivo})],
  ['valor','Propostas sem valor',null,X.filter(function(l){return l.status==='proposta'&&!l.valor})],
  ['atras','Retornos atrasados',null,X.filter(function(l){return ativo(l)&&l.retorno&&l.retorno<h})]];
 var tot=P.reduce(function(a,p){return a+p[3].length},0),U={};P.forEach(function(p){if(p[0]==='dup')p[3].forEach(function(g){g.forEach(function(l){U[l.id]=1})});else p[3].forEach(function(l){U[l.id]=1})});var nota=Math.max(0,100-Math.round(Object.keys(U).length/Math.max(1,X.length)*100));
 $('c-body').innerHTML="<div class='kpi-row'><div class='kpi'><div class='kpi-label'>Saúde do CRM</div><div class='kpi-val'>"+nota+"<small style='font-size:14px'>/100</small></div></div><div class='kpi'><div class='kpi-label'>Pendências</div><div class='kpi-val'>"+tot+"</div></div><div class='kpi'><div class='kpi-label'>Leads</div><div class='kpi-val'>"+X.length+"</div></div></div>"
 +P.map(function(p){var n=p[3].length;return "<div class='card' style='margin-top:10px'><div class='card-header' style='display:flex;justify-content:space-between;align-items:center;cursor:pointer' onclick=\"var b=this.nextSibling;b.style.display=b.style.display==='none'?'block':'none'\"><div class='card-title'>"+(n?'Pendente · ':'OK · ')+p[1]+"</div><b>"+(p[2]||n)+"</b></div><div class='card-body' style='display:none'>"+(n?fxList(p[0],p[3]):"<small>Tudo certo.</small>")+"</div></div>"}).join('')}
function fxRow(l,extra){return "<div style='display:flex;justify-content:space-between;gap:8px;align-items:center;padding:8px 0;border-bottom:1px solid #efe9df;font-size:12.5px'><span><b style='cursor:pointer' onclick='verPerfil("+l.id+")'>"+esc(l.nome)+"</b><br><small>"+esc([l.tel,l.bairro,l.status,l.fonte||l.origem].filter(Boolean).join(' · '))+"</small></span><span style='white-space:nowrap'>"+extra+"</span></div>"}
function fxList(k,A){if(k==='dup')return A.map(function(g){return "<div style='border:1px solid #efe9df;border-radius:4px;padding:8px;margin-bottom:8px'>"+g.map(function(l){return fxRow(l,'')}).join('')+"<button class='btn-submit' style='margin-top:6px' onclick='fxMerge(["+g.map(function(l){return l.id}).join(',')+"])'>Unir em um só</button></div>"}).join('');
 var ed=function(l){return "<button class='btn-cancel' onclick='editarLead("+l.id+")'>Corrigir</button>"};
 if(k==='bairro')return "<div style='display:flex;gap:6px;margin-bottom:8px'><input class='form-input' id='fx-b' list='sc-bl' placeholder='Bairro para todos'/><button class='btn-submit' onclick='fxMass(\"bairro\")'>Aplicar a todos</button></div>"+A.map(function(l){return fxRow(l,ed(l))}).join('');
 if(k==='fonte')return "<div style='display:flex;gap:6px;margin-bottom:8px'><input class='form-input' id='fx-f' placeholder='Fonte para todos (ex.: Lista antiga)'/><button class='btn-submit' onclick='fxMass(\"fonte\")'>Aplicar a todos</button></div>"+A.map(function(l){return fxRow(l,ed(l))}).join('');
 if(k==='parado'||k==='atras'||k==='novo')return "<button class='btn-submit' style='margin-bottom:8px' onclick='fxFila(\""+k+"\")'>Ligar para todos no discador</button>"+A.map(function(l){return fxRow(l,"<button class='btn-cancel' onclick='ligar("+l.id+")'>Ligar</button> <button class='btn-cancel' onclick='zap("+l.id+")'>WhatsApp</button>")}).join('');
 if(k==='tel')return A.map(function(l){return fxRow(l,ed(l)+" <button class='btn-cancel' onclick='if(confirm(\"Excluir?\")){saveLeads(getLeads().filter(function(x){return x.id!="+l.id+"}));tab(\"faxina\")}'>Excluir</button>")}).join('');
 return A.map(function(l){return fxRow(l,ed(l))}).join('')}
window.fxMerge=function(ids){var X=L(),G=X.filter(function(l){return ids.indexOf(l.id)>=0}).sort(function(a,b){return a.id-b.id}),m=G[0];
 G.slice(1).forEach(function(o){['nome','email','bairro','fonte','origem','renda','fgts','valor','interesse','retorno'].forEach(function(k){if(!m[k]&&o[k])m[k]=o[k]});if(o.nome&&o.nome!=='Contato'&&(m.nome==='Contato'||!m.nome))m.nome=o.nome;if(o.temp==='quente')m.temp='quente';m.hist=(m.hist||[]).concat(o.hist||[]);m.tags=(m.tags||[]).concat(o.tags||[]).filter(function(v,i,a){return a.indexOf(v)===i})});
 (m.hist=m.hist||[]).unshift({a:'Duplicados unidos',d:G.length+' registros',t:new Date().toLocaleString('pt-BR')});S(X.filter(function(l){return ids.indexOf(l.id)<0||l.id===m.id}));toast('Unidos em 1 lead');tab('faxina')};
window.fxMass=function(k){var v=$(k==='bairro'?'fx-b':'fx-f').value.trim();if(!v)return;var X=L(),n=0;X.forEach(function(l){if(k==='bairro'&&!l.bairro&&l.status!=='perdido'&&l.status!=='fechado'){l.bairro=v;n++}if(k==='fonte'&&!(l.fonte||l.origem)){l.fonte=l.origem=v;n++}});S(X);toast(n+' corrigido(s)');tab('faxina')};
window.fxFila=function(k){var X=L(),h=iso();window.__fila=X.filter(function(l){var a=l.status!=='perdido'&&l.status!=='fechado';if(!a||!String(l.tel||'').replace(/\D/g,''))return false;if(k==='parado')return dias(l)>=7&&!(l.retorno&&l.retorno>=h);if(k==='atras')return l.retorno&&l.retorno<h;return (l.status||'novo')==='novo'&&dias(l)>=3});window.__fi=0;goPage('discador');setTimeout(function(){discProx(0)},120)};
/* ---------- importar CSV ---------- */
window.importarCSV=function(){var i=document.createElement('input');i.type='file';i.accept='.csv,text/csv,.txt';i.onchange=function(){var r=new FileReader();r.onload=function(){var lines=String(r.result).split(/\r?\n/).filter(Boolean),sep=(lines[0].match(/;/g)||[]).length>(lines[0].match(/,/g)||[]).length?';':',',hd=lines[0].split(sep).map(sa);
 var ix=function(re){for(var k=0;k<hd.length;k++)if(re.test(hd[k]))return k;return -1},iN=ix(/nome|name/),iT=ix(/tel|cel|fone|whats|phone/),iE=ix(/mail/),iB=ix(/bairro|regiao|cidade/);
 if(iN<0&&iT<0){alert('Não achei colunas de nome/telefone na primeira linha.');return}var f=prompt('Fonte desta planilha (obrigatório):');if(!f)return;var X=L(),ex={},n=0;X.forEach(function(l){ex[String(l.tel).replace(/\D/g,'').slice(-9)]=1});
 lines.slice(1).forEach(function(ln,k){var c=ln.split(sep).map(function(x){return x.replace(/^"|"$/g,'').trim()}),t=(c[iT]||'').replace(/\D/g,'');if(!t&&!c[iE])return;if(t&&ex[t.slice(-9)])return;ex[t.slice(-9)]=1;
  X.unshift({id:Date.now()+k,nome:c[iN]||'Contato',tel:t,email:iE>=0?c[iE]:'',bairro:iB>=0?c[iB]:'',fonte:f,origem:f,interesse:'A definir',temp:'frio',status:'novo',data:new Date().toLocaleDateString('pt-BR'),hist:[{a:'Importado de planilha',d:f,t:new Date().toLocaleString('pt-BR')}]});n++});
 S(X);toast(n+' lead(s) importado(s) (duplicados ignorados)');if(window.__ct)tab('leads')};r.readAsText(i.files[0],'UTF-8')};i.click()};
/* ---------- backup automático, saída por inatividade, LGPD, atalhos, modo escuro, app ---------- */
try{var k='crm_bak_'+iso();if(!localStorage.getItem(k)){localStorage.setItem(k,JSON.stringify({l:L(),i:getImoveis()}));Object.keys(localStorage).filter(function(x){return /^crm_bak_/.test(x)}).sort().slice(0,-7).forEach(function(x){localStorage.removeItem(x)})}}catch(e){}
window.restaurarBackup=function(){var ks=Object.keys(localStorage).filter(function(x){return /^crm_bak_/.test(x)}).sort().reverse();var d=prompt('Backups disponíveis:\n'+ks.map(function(x){return x.slice(8)}).join('\n')+'\n\nDigite a data (aaaa-mm-dd) para restaurar:');if(!d||!localStorage['crm_bak_'+d])return;if(!confirm('Substituir os dados atuais pelo backup de '+d+'?'))return;var b=JSON.parse(localStorage['crm_bak_'+d]);saveLeads(b.l);saveImoveis(b.i);location.reload()};
var idle;function reset(){clearTimeout(idle);idle=setTimeout(function(){localStorage.removeItem('crm_auth');location.reload()},4*3600e3)}['click','keydown','touchstart'].forEach(function(e){document.addEventListener(e,reset,{passive:true})});reset();
document.addEventListener('keydown',function(e){if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)||e.ctrlKey||e.metaKey||e.altKey)return;var k=e.key.toLowerCase();if(k==='n'){goPage('novo-lead')}else if(k==='c'){goPage('central')}else if(k==='d'){goPage('discador')}else if(k==='s'){abrirImportFoto()}else if(k==='/'){e.preventDefault();goPage('central');setTimeout(function(){var q=$('f-q');q&&q.focus()},60)}});
function dark(on){var s=$('crm-dark');if(on&&!s){s=document.createElement('style');s.id='crm-dark';s.textContent='body{background:#121110!important;color:#ece6da!important}.card,.kpi,.icard,.pipe-col,.modal,.topbar,.lead-table th,.form-input,.form-select,.btn-cancel,.pipe-card{background:#1c1b19!important;color:#ece6da!important;border-color:#2c2b28!important}.kpi-val,.card-title,.topbar-title,.lead-name,.page-title{color:#f4efe6!important}';document.head.appendChild(s)}if(!on&&s)s.remove();localStorage.crm_dark=on?'1':''}
dark(localStorage.crm_dark==='1');
/* menu */
var _gp=window.goPage;window.goPage=function(p){if(p==='central')central();_gp.apply(this,arguments);if(p==='central'){$('topbar-title').textContent='Central de vendas';var pg=$('page-central');document.querySelectorAll('.page').forEach(function(x){x.classList.remove('active')});pg.classList.add('active')}};
setTimeout(function(){var nav=document.querySelector('.sb-nav')||document.querySelector('.sb-link')&&document.querySelector('.sb-link').parentNode;if(nav&&!$('sb-central')){var a=document.createElement('div');a.className='sb-link';a.id='sb-central';a.setAttribute('onclick',"goPage('central')");a.textContent='Central de vendas';nav.insertBefore(a,nav.firstChild);
 var e=document.createElement('div');e.className='sb-link';e.textContent='Modo escuro / claro';e.onclick=function(){dark(localStorage.crm_dark!=='1')};nav.appendChild(e);
 var r=document.createElement('div');r.className='sb-link';r.textContent='Restaurar backup';r.onclick=restaurarBackup;nav.appendChild(r)}
 if(!document.querySelector('link[rel=manifest]')){var m=document.createElement('link');m.rel='manifest';m.href=(location.pathname.indexOf('/adm/')>=0?'../':'')+'crm-manifest.json';document.head.appendChild(m);var t=document.createElement('meta');t.name='theme-color';t.content='#141311';document.head.appendChild(t)}},400);
})();
